version: '3.8'
services:
    postgres:
        image: ${COMPOSE_NAME}/${DATABASE_IMAGE}
        build:
            context: .
            dockerfile: ./apps/postgres/Dockerfile
            args:
                - POSTGRES_VERSION=${POSTGRES_VERSION}
                - POSTGRES_USER_FILE=${POSTGRES_USER}
                - POSTGRES_PASSWORD_FILE=${POSTGRES_PASSWORD}
                - WORKINGDIR=${WORKINGDIR}
        container_name: ${COMPOSE_NAME}.${DATABASE_IMAGE}
        environment:
            - POSTGRES_USER_FILE=${POSTGRES_USER_FILE}
            - POSTGRES_PASSWORD_FILE=${POSTGRES_PASSWORD_FILE}
            - POSTGRES_DB=${POSTGRES_DB}
        networks:
            - 'ambrosia-loans'
        volumes:
            - ${MOUNT}/database:/var/lib/postgresql/data
        ports:
            - '5432:5432'
    api:
        image: ${COMPOSE_NAME}/${API_IMAGE}
        container_name: ${COMPOSE_NAME}.${API_IMAGE}
        depends_on:
            - postgres
        build:
            context: .
            dockerfile: ./apps/api/Dockerfile
            args:
                - WORKINGDIR=${WORKINGDIR}
                - COMPOSE_NAME=${COMPOSE_NAME}
                - BASE_IMAGE=${BASE_IMAGE}
                - NODE_VERSION=${NODE_VERSION}
        networks:
            - 'ambrosia-loans'
        environment:
            - PORT=${NGINX_PORT}
            - WORKINGDIR=${WORKINGDIR}
    website:
        image: ${COMPOSE_NAME}/${WEBSITE_IMAGE}
        container_name: ${COMPOSE_NAME}.${WEBSITE_IMAGE}
        build:
            context: .
            dockerfile: ./apps/website/Dockerfile
            args:
                - WORKINGDIR=${WORKINGDIR}
                - COMPOSE_NAME=${COMPOSE_NAME}
                - BASE_IMAGE=${BASE_IMAGE}
                - NGINX_VERSION=${NGINX_VERSION}
                - NGINX_PORT=${NGINX_PORT}
        networks:
            - 'ambrosia-loans'
        environment:
            - PORT=${NGINX_PORT}
            - WORKINGDIR=${WORKINGDIR}
            - NGINX_PORT=${NGINX_PORT}
    nginx:
        depends_on:
            - website
            - api
        container_name: ${COMPOSE_NAME}.${NGINX_IMAGE}
        image: ${COMPOSE_NAME}/${NGINX_IMAGE}
        build:
            context: .
            dockerfile: ./apps/nginx/Dockerfile
            args:
                - WORKINGDIR=${WORKINGDIR}
                - NGINX_VERSION=${NGINX_VERSION}
        networks:
            - 'appleptr16'
            - 'ambrosia-loans'
        environment:
            - WEBSITE_DOMAIN=${WEBSITE_DOMAIN}
            - WEBSITE_IMAGE=${WEBSITE_IMAGE}
            - API_DOMAIN=${API_DOMAIN}
            - API_IMAGE=${API_IMAGE}

            - COMPOSE_NAME=${COMPOSE_NAME}
            - DOMAIN_PREFIX=${DOMAIN_PREFIX}
            - NGINX_PORT=${NGINX_PORT}

            - WORKINGDIR=${WORKINGDIR}
        ports:
            - '${NGINX_PORT}:${NGINX_PORT}'
networks:
    ambrosia-loans:
        name: ambrosia-loans
    appleptr16:
        name: appleptr16
