version: '3.8'
services:
    postgres:
        restart: unless-stopped
        image: docker.appleptr16.com/${COMPOSE_NAME}/${DATABASE_IMAGE}:${MAIN_VERSION}
        container_name: ${COMPOSE_NAME}.${DATABASE_IMAGE}
        environment:
            - POSTGRES_USER_FILE=${POSTGRES_USER_FILE}
            - POSTGRES_PASSWORD_FILE=${POSTGRES_PASSWORD_FILE}
            - POSTGRES_DB=${POSTGRES_DB}
        networks:
            - 'ambrosia-loans'
        volumes:
            - ${MOUNT}/database:/${WORKINGDIR}/database
    api:
        restart: unless-stopped
        image: docker.appleptr16.com/${COMPOSE_NAME}/${API_IMAGE}:${MAIN_VERSION}
        container_name: ${COMPOSE_NAME}.${API_IMAGE}
        depends_on:
            - postgres
        networks:
            - 'ambrosia-loans'
        environment:
            - PORT=${NGINX_PORT}
            - WORKINGDIR=${WORKINGDIR}
    website:
        restart: unless-stopped
        image: docker.appleptr16.com/${COMPOSE_NAME}/${WEBSITE_IMAGE}:${MAIN_VERSION}
        container_name: ${COMPOSE_NAME}.${WEBSITE_IMAGE}
        networks:
            - 'ambrosia-loans'
        environment:
            - PORT=${NGINX_PORT}
            - WORKINGDIR=${WORKINGDIR}
            - NGINX_PORT=${NGINX_PORT}
    nginx:
        restart: unless-stopped
        depends_on:
            - website
            - api
        container_name: ${COMPOSE_NAME}.${NGINX_IMAGE}
        image: docker.appleptr16.com/${COMPOSE_NAME}/${NGINX_IMAGE}:${MAIN_VERSION}
        networks:
            - 'appleptr16'
            - 'ambrosia-loans'
        environment:
            - WEBSITE_DOMAIN=${WEBSITE_DOMAIN}
            - WEBSITE_IMAGE=${WEBSITE_IMAGE}
            - API_DOMAIN=${API_DOMAIN}
            - API_IMAGE=${API_IMAGE}

            - COMPOSE_NAME=${COMPOSE_NAME}
            - DOMAIN_PREFIX=${DOMAIN_PREFIX}
            - NGINX_PORT=${NGINX_PORT}
            - WORKINGDIR=${WORKINGDIR}
        ports:
            - '${NGINX_PORT}:${NGINX_PORT}'
networks:
    ambrosia-loans:
        name: ambrosia-loans
    appleptr16:
        name: appleptr16
